#+TITLE: MySQL Notes

Notes on MySQL with especial applicability to the Tiki

* MySQL Notes

** MySQL Client Programs

#+BEGIN_SRC sh
mysql -u{USER} -p[{PW}] [{DBNAME}] [< {FILE-TO-IMPORT}.sql]
mysqldump -u{USER} -p[{PW}] {DBNAME} [{TABLE}...] > {BACKUP_FILE}.sql
mysqldump --opt --all-databases > {BACKUP_FILE}.sql
#+END_SRC

** MySQL Meta Queries

#+BEGIN_SRC sql
\r [db] [host] -- (re)connect
-- Remove prompt with \R<space><enter>
\R
STATUS;
USE database_name;
HELP SHOW;
SHOW databases;
SHOW tables;
SHOW FUNCTION STATUS;
SHOW CREATE FUNCTION <name>;
SHOW PROCEDURE STATUS;

SHOW PROCEDURE STATUS WHERE db = DATABASE();
SHOW PROCEDURE STATUS WHERE db = 'databasename';
SHOW CREATE PROCEDURE <name>;
SELECT ROUTINE_NAME, ROUTINE_TYPE FROM INFORMATION_SCHEMA.ROUTINES;
DESCRIBE INFORMATION_SCHEMA.ROUTINES;
DESCRIBE <table name>; -- SHOW COLUMNS FROM database-name
CREATE DATABASE <db name>;
SOURCE {INPUT_FILE};
#+END_SRC

** phpMyAdmin

*** How can I connect on a?

https://askubuntu.com/questions/763336/cannot-enter-phpmyadmin-as-root-mysql-5-7


MySQL 5.7 changed the secure model: now MySQL root login requires a sudo (while the password still can be blank).

I.e., phpMyAdmin will be not able to use root as user.

The simplest (and safest) solution will be create a new user and grant required privileges.

#+BEGIN_SRC sql
GRANT ALL PRIVILEGES ON *.* TO 'phpmyadmin'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
#+END_SRC

*** How can we securely connect on ngender.org?

** mycli

I installed mycli on a

No man page or other documentation, not even useful --help

Research or uninstall it!

** https://en.wikibooks.org/wiki/MySQL/CheatSheet

Forgot root password?
#+BEGIN_SRC sh
service mysql stop
mysqld_safe --skip-grant-tables &
mysql # on another terminal
mysql> UPDATE mysql.user SET password=PASSWORD('nouveau') WHERE user='root';
## Kill mysqld_safe from the terminal, using Control + \
service start mysql
#+END_SRC

Repair tables after unclean shutdown

#+BEGIN_SRC sh
mysqlcheck --all-databases
mysqlcheck --all-databases --fast
#+END_SRC

** MySql Functions and Operators

#+BEGIN_SRC sql
-- https://dev.mysql.com/doc/refman/5.7/en/string-functions.html
-- http://www.w3resource.com/mysql/mysql-functions-and-operators.php
CONCAT( arg1, arg2, .. )
TRIM([{BOTH | LEADING | TRAILING} [remstr] FROM] str), TRIM([remstr FROM] str)
#+END_SRC

** MySql Commands

*** Checking and repairing mysql tables and databases

mysqlcheck -c tiki -u phpmyadmin -p

*** Emacs as a Client

https://stackoverflow.com/questions/17246119/emacs-how-to-use-ssh-tunnel-to-connect-to-remote-mysql

(sql-default-directory "/host.myhost.com:")

*** MySQL UPDATE

#+BEGIN_SRC sql
-- Single-table syntax:
UPDATE [LOW_PRIORITY] [IGNORE] table_reference
    SET col_name1={expr1|DEFAULT} [, col_name2={expr2|DEFAULT}] ...
    [WHERE where_condition]
    [ORDER BY ...]
    [LIMIT row_count]

-- Multiple-table syntax:

UPDATE [LOW_PRIORITY] [IGNORE] table_references
    SET col_name1={expr1|DEFAULT} [, col_name2={expr2|DEFAULT}] ...
    [WHERE where_condition]
#+END_SRC

There are no FROM clauses in MySQL UPDATE so the
Multiple-table syntax has to be used to introduce any
additional tables involved in the WHERE constraints.

** MySql Backup & Recovery
*** Backup Options
Note options used in 

mysqldump --routines --all-databases --add-drop-database \
--add-locks --extended-insert -

*** Password Changes & Recovery

**** Privileges are cached

flush previleges; -- for changes to take effect


Fist you can check your access.

1.- Check for your access in the new server

$mysql -u root -p -hlocalhost

Enter password:

2.- show your grants

$mysql>SHOW GRANTS FOR 'root'@'localhost';

To solve the problem you can do this.

1.- stop your services.

service mysqld stop

2.- start your services with "stop grant tables"

mysqld --skip-grant-tables

3.-update the password of user root

$mysql>UPDATE user SET Password=PASSWORD('my_password') where USER='root';

(if you want you can create your user) $mysql>CREATE USER 'root'@'localhost' IDENTIFIED BY 'password';

4.- Flush the privilages

$mysql> FLUSH PRIVILEGES;

5.- Restart your server

service mysqld start



* Tiki Database Problems
There seem to be some DATA CORRUPTIONS as shown by:
#+BEGIN_SRC sh
	SELECT * FROM tiki_categorized_objects t
	LEFT JOIN tiki_objects ON (catObjectId=objectId)
	WHERE t.catObjectId	NOT IN (SELECT catObjectId FROM tiki_category_objects);
#+END_SRC
MariaDB [tiki]> +-------------+----------+------+--------+-------------+---------+------+------+------+-----------------+
| catObjectId | objectId | type | itemId | description | created | name | href | hits | comments_locked |
+-------------+----------+------+--------+-------------+---------+------+------+------+-----------------+
|         138 |     NULL | NULL | NULL   | NULL        |    NULL | NULL | NULL | NULL | NULL            |
|         145 |     NULL | NULL | NULL   | NULL        |    NULL | NULL | NULL | NULL | NULL            |
|         157 |     NULL | NULL | NULL   | NULL        |    NULL | NULL | NULL | NULL | NULL            |
|         163 |     NULL | NULL | NULL   | NULL        |    NULL | NULL | NULL | NULL | NULL            |
+-------------+----------+------+--------+-------------+---------+------+------+------+-----------------+
4 rows in set (0.00 sec)

* MySQL Techniques

** Upsert

- [[https://www.xaprb.com/blog/2006/02/21/flexible-insert-and-update-in-mysql/][flexible-insert-and-update-in-mysql]]

** Simple Select Function

#+BEGIN_SRC sql
DROP FUNCTION IF EXISTS `group_default_category`;
DELIMITER //
CREATE DEFINER=`phpmyadmin`@`localhost`
	FUNCTION `group_default_category`(group_ int(11))
	RETURNS int(12)	READS SQL DATA
BEGIN
	DECLARE found_ int(12) DEFAULT 0;
	SELECT groupDefCat INTO found_ FROM users_groups WHERE id = group_;
	RETURN found_;
END//
DELIMITER ;
#+END_SRC

** Fancy Select Function

#+BEGIN_SRC sql
-- THIS IS OVERKILL FOR THIS PURPOSE - KEEP FOR REFERENCE!
DROP FUNCTION IF EXISTS `group_default_category_overkill`;
DELIMITER //
CREATE DEFINER=`phpmyadmin`@`localhost`
	FUNCTION `group_default_category_overkill`(group_ int(11))
	RETURNS int(12)	READS SQL DATA
BEGIN
	DECLARE found_ int(12);
	DECLARE failed_ boolean DEFAULT false;
	DEClARE cursor_ CURSOR FOR 
	SELECT groupDefCat FROM users_groups WHERE id = group_;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET failed_ = true;
	OPEN cursor_;
  FETCH cursor_ INTO found_;
  IF failed_ THEN CLOSE cursor_; RETURN 0;
	ELSE CLOSE cursor_; RETURN found_;
	END IF;
END//
DELIMITER ;
#+END_SRC

** While Loop in Function

#+BEGIN_SRC sql
DROP FUNCTION IF EXISTS `category_path`;
DELIMITER //
CREATE DEFINER=`phpmyadmin`@`localhost`
FUNCTION `category_path`(category_id int(11))
RETURNS varchar(200) READS SQL DATA
BEGIN
	DECLARE path_ varchar(200) DEFAULT category_name(category_id);
	DECLARE parent_ int(11) DEFAULT category_parent(category_id);
	WHILE parent_ > 0 DO
		SET path_ = CONCAT(category_name(parent_), '::', path_);
		SET parent_ = category_parent(parent_);
	END WHILE;
	RETURN path_;
END//
DELIMITER ;
#+END_SRC

** Exceptions

delimiter //
CREATE FUNCTION f () RETURNS INT
BEGIN
  SIGNAL SQLSTATE '01234';  -- signal a warning
  RETURN 5;
END//
delimiter ;
CREATE TABLE t (s1 INT);
INSERT INTO t VALUES (f());

Having trouble suppressing the result set from EXECUTE

These didn't work:
- 'SET @foo = ', expression_
- 'SELECT ', expression_
- 'SELECT ', expression_, ' INTO @foo'
- Is the problem somewhere else?

These did:
- 'CALL chuck_text_(CONCAT(', expression_, '))'
- 'CALL chuck_int_(', expression_, 'IS NOT NULL)'

given

#+BEGIN_SRC sql
DROP PROCEDURE IF EXISTS `chuck_int_`;
DELIMITER //
CREATE DEFINER=`phpmyadmin`@`localhost`
PROCEDURE `chuck_int_`(value_ INT)
	COMMENT 'throw away the argument'
BEGIN
END//
DELIMITER ;
#+END_SRC
